@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedEntityStatisticMap
Class JsonAdaptedTag
}

package "MatchRecord Storage" #F4F6F6{
Class "<<interface>>\nMatchRecordStorage" as MatchRecordStorage
Class JsonMatchRecordStorage
Class JsonSerializableMatchRecord
Class JsonAdaptedMatch
}

package "Entity Storage" #F4F6F6{
Class "<<interface>>\nEntityStorage" as EntityStorage
Class JsonEntityStorage
Class JsonAdaptedEntityPathPair
}


}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" MatchRecordStorage
StorageManager -up-> "1" EntityStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage
Storage -right-|> MatchRecordStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonAdaptedPerson --> "1" JsonAdaptedEntityStatisticMap

JsonMatchRecordStorage .up.|> MatchRecordStorage
JsonMatchRecordStorage ..> JsonSerializableMatchRecord
JsonSerializableMatchRecord --> "*" JsonAdaptedMatch

JsonEntityStorage .up.|> EntityStorage
JsonEntityStorage --> "*" JsonAdaptedEntityPathPair

@enduml
