package seedu.address.model.util;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import seedu.address.model.entity.Entity;
import seedu.address.model.entity.EntityPathPair;

/**
 * Contains utility methods for populating {@code EntityReference} with sample data.
 */
public class SampleEntityUtil {

    private SampleEntityUtil() {} // Prevent instantiation

    /**
     * Returns a list of sample entities.
     * This contains every champion in League of Legends, as of 6/4/2026.
     */
    public static List<EntityPathPair> getSampleEntities() {
        List<EntityPathPair> entities = new ArrayList<>();
        entities.add(new EntityPathPair(new Entity("Aatrox"), Path.of("/images/aatrox.png")));
        entities.add(new EntityPathPair(new Entity("Ahri"), Path.of("/images/ahri.png")));
        entities.add(new EntityPathPair(new Entity("Akali"), Path.of("/images/akali.png")));
        entities.add(new EntityPathPair(new Entity("Ambessa"), Path.of("/images/ambessa.png")));
        entities.add(new EntityPathPair(new Entity("Akshan"), Path.of("/images/akshan.png")));
        entities.add(new EntityPathPair(new Entity("Alistar"), Path.of("/images/alistar.png")));
        entities.add(new EntityPathPair(new Entity("Amumu"), Path.of("/images/amumu.png")));
        entities.add(new EntityPathPair(new Entity("Anivia"), Path.of("/images/anivia.png")));
        entities.add(new EntityPathPair(new Entity("Annie"), Path.of("/images/annie.png")));
        entities.add(new EntityPathPair(new Entity("Aphelios"), Path.of("/images/aphelios.png")));
        entities.add(new EntityPathPair(new Entity("Ashe"), Path.of("/images/ashe.png")));
        entities.add(new EntityPathPair(new Entity("Aurelion Sol"), Path.of("/images/aurelionsol.png")));
        entities.add(new EntityPathPair(new Entity("Aurora"), Path.of("/images/aurora.png")));
        entities.add(new EntityPathPair(new Entity("Azir"), Path.of("/images/azir.png")));
        entities.add(new EntityPathPair(new Entity("Bard"), Path.of("/images/bard.png")));
        entities.add(new EntityPathPair(new Entity("Briar"), Path.of("/images/briar.png")));
        entities.add(new EntityPathPair(new Entity("Bel'Veth"), Path.of("/images/belveth.png")));
        entities.add(new EntityPathPair(new Entity("Blitzcrank"), Path.of("/images/blitzcrank.png")));
        entities.add(new EntityPathPair(new Entity("Brand"), Path.of("/images/brand.png")));
        entities.add(new EntityPathPair(new Entity("Braum"), Path.of("/images/braum.png")));
        entities.add(new EntityPathPair(new Entity("Caitlyn"), Path.of("/images/caitlyn.png")));
        entities.add(new EntityPathPair(new Entity("Camille"), Path.of("/images/camille.png")));
        entities.add(new EntityPathPair(new Entity("Cassiopeia"), Path.of("/images/cassiopeia.png")));
        entities.add(new EntityPathPair(new Entity("Cho'Gath"), Path.of("/images/chogath.png")));
        entities.add(new EntityPathPair(new Entity("Corki"), Path.of("/images/corki.png")));
        entities.add(new EntityPathPair(new Entity("Darius"), Path.of("/images/darius.png")));
        entities.add(new EntityPathPair(new Entity("Diana"), Path.of("/images/diana.png")));
        entities.add(new EntityPathPair(new Entity("Draven"), Path.of("/images/draven.png")));
        entities.add(new EntityPathPair(new Entity("Dr. Mundo"), Path.of("/images/drmundo.png")));
        entities.add(new EntityPathPair(new Entity("Ekko"), Path.of("/images/ekko.png")));
        entities.add(new EntityPathPair(new Entity("Elise"), Path.of("/images/elise.png")));
        entities.add(new EntityPathPair(new Entity("Evelynn"), Path.of("/images/evelynn.png")));
        entities.add(new EntityPathPair(new Entity("Ezreal"), Path.of("/images/ezreal.png")));
        entities.add(new EntityPathPair(new Entity("Fiddlesticks"), Path.of("/images/fiddlesticks.png")));
        entities.add(new EntityPathPair(new Entity("Fiora"), Path.of("/images/fiora.png")));
        entities.add(new EntityPathPair(new Entity("Fizz"), Path.of("/images/fizz.png")));
        entities.add(new EntityPathPair(new Entity("Galio"), Path.of("/images/galio.png")));
        entities.add(new EntityPathPair(new Entity("Gangplank"), Path.of("/images/gangplank.png")));
        entities.add(new EntityPathPair(new Entity("Garen"), Path.of("/images/garen.png")));
        entities.add(new EntityPathPair(new Entity("Gnar"), Path.of("/images/gnar.png")));
        entities.add(new EntityPathPair(new Entity("Gragas"), Path.of("/images/gragas.png")));
        entities.add(new EntityPathPair(new Entity("Graves"), Path.of("/images/graves.png")));
        entities.add(new EntityPathPair(new Entity("Gwen"), Path.of("/images/gwen.png")));
        entities.add(new EntityPathPair(new Entity("Hecarim"), Path.of("/images/hecarim.png")));
        entities.add(new EntityPathPair(new Entity("Hwei"), Path.of("/images/hwei.png")));
        entities.add(new EntityPathPair(new Entity("Heimerdinger"), Path.of("/images/heimerdinger.png")));
        entities.add(new EntityPathPair(new Entity("Illaoi"), Path.of("/images/illaoi.png")));
        entities.add(new EntityPathPair(new Entity("Irelia"), Path.of("/images/irelia.png")));
        entities.add(new EntityPathPair(new Entity("Ivern"), Path.of("/images/ivern.png")));
        entities.add(new EntityPathPair(new Entity("Janna"), Path.of("/images/janna.png")));
        entities.add(new EntityPathPair(new Entity("Jarvan IV"), Path.of("/images/jarvaniv.png")));
        entities.add(new EntityPathPair(new Entity("Jax"), Path.of("/images/jax.png")));
        entities.add(new EntityPathPair(new Entity("Jayce"), Path.of("/images/jayce.png")));
        entities.add(new EntityPathPair(new Entity("Jhin"), Path.of("/images/jhin.png")));
        entities.add(new EntityPathPair(new Entity("Jinx"), Path.of("/images/jinx.png")));
        entities.add(new EntityPathPair(new Entity("Kai'Sa"), Path.of("/images/kaisa.png")));
        entities.add(new EntityPathPair(new Entity("Kalista"), Path.of("/images/kalista.png")));
        entities.add(new EntityPathPair(new Entity("Karma"), Path.of("/images/karma.png")));
        entities.add(new EntityPathPair(new Entity("Karthus"), Path.of("/images/karthus.png")));
        entities.add(new EntityPathPair(new Entity("Kassadin"), Path.of("/images/kassadin.png")));
        entities.add(new EntityPathPair(new Entity("Katarina"), Path.of("/images/katarina.png")));
        entities.add(new EntityPathPair(new Entity("Kayle"), Path.of("/images/kayle.png")));
        entities.add(new EntityPathPair(new Entity("Kayn"), Path.of("/images/kayn.png")));
        entities.add(new EntityPathPair(new Entity("Kennen"), Path.of("/images/kennen.png")));
        entities.add(new EntityPathPair(new Entity("Kha'Zix"), Path.of("/images/khazix.png")));
        entities.add(new EntityPathPair(new Entity("K'Sante"), Path.of("/images/ksante.png")));
        entities.add(new EntityPathPair(new Entity("Kindred"), Path.of("/images/kindred.png")));
        entities.add(new EntityPathPair(new Entity("Kled"), Path.of("/images/kled.png")));
        entities.add(new EntityPathPair(new Entity("Kog'Maw"), Path.of("/images/kogmaw.png")));
        entities.add(new EntityPathPair(new Entity("LeBlanc"), Path.of("/images/leblanc.png")));
        entities.add(new EntityPathPair(new Entity("Lee Sin"), Path.of("/images/leesin.png")));
        entities.add(new EntityPathPair(new Entity("Leona"), Path.of("/images/leona.png")));
        entities.add(new EntityPathPair(new Entity("Lillia"), Path.of("/images/lillia.png")));
        entities.add(new EntityPathPair(new Entity("Lissandra"), Path.of("/images/lissandra.png")));
        entities.add(new EntityPathPair(new Entity("Lucian"), Path.of("/images/lucian.png")));
        entities.add(new EntityPathPair(new Entity("Lulu"), Path.of("/images/lulu.png")));
        entities.add(new EntityPathPair(new Entity("Lux"), Path.of("/images/lux.png")));
        entities.add(new EntityPathPair(new Entity("Malphite"), Path.of("/images/malphite.png")));
        entities.add(new EntityPathPair(new Entity("Malzahar"), Path.of("/images/malzahar.png")));
        entities.add(new EntityPathPair(new Entity("Maokai"), Path.of("/images/maokai.png")));
        entities.add(new EntityPathPair(new Entity("Master Yi"), Path.of("/images/masteryi.png")));
        entities.add(new EntityPathPair(new Entity("Mel"), Path.of("/images/mel.png")));
        entities.add(new EntityPathPair(new Entity("Miss Fortune"), Path.of("/images/missfortune.png")));
        entities.add(new EntityPathPair(new Entity("Milio"), Path.of("/images/milio.png")));
        entities.add(new EntityPathPair(new Entity("Mordekaiser"), Path.of("/images/mordekaiser.png")));
        entities.add(new EntityPathPair(new Entity("Morgana"), Path.of("/images/morgana.png")));
        entities.add(new EntityPathPair(new Entity("Nami"), Path.of("/images/nami.png")));
        entities.add(new EntityPathPair(new Entity("Naafiri"), Path.of("/images/naafiri.png")));
        entities.add(new EntityPathPair(new Entity("Nasus"), Path.of("/images/nasus.png")));
        entities.add(new EntityPathPair(new Entity("Nautilus"), Path.of("/images/nautilus.png")));
        entities.add(new EntityPathPair(new Entity("Neeko"), Path.of("/images/neeko.png")));
        entities.add(new EntityPathPair(new Entity("Nidalee"), Path.of("/images/nidalee.png")));
        entities.add(new EntityPathPair(new Entity("Nilah"), Path.of("/images/nilah.png")));
        entities.add(new EntityPathPair(new Entity("Nocturne"), Path.of("/images/nocturne.png")));
        entities.add(new EntityPathPair(new Entity("Nunu & Willump"), Path.of("/images/nunu.png")));
        entities.add(new EntityPathPair(new Entity("Olaf"), Path.of("/images/olaf.png")));
        entities.add(new EntityPathPair(new Entity("Orianna"), Path.of("/images/orianna.png")));
        entities.add(new EntityPathPair(new Entity("Ornn"), Path.of("/images/ornn.png")));
        entities.add(new EntityPathPair(new Entity("Pantheon"), Path.of("/images/pantheon.png")));
        entities.add(new EntityPathPair(new Entity("Poppy"), Path.of("/images/poppy.png")));
        entities.add(new EntityPathPair(new Entity("Pyke"), Path.of("/images/pyke.png")));
        entities.add(new EntityPathPair(new Entity("Qiyana"), Path.of("/images/qiyana.png")));
        entities.add(new EntityPathPair(new Entity("Quinn"), Path.of("/images/quinn.png")));
        entities.add(new EntityPathPair(new Entity("Rakan"), Path.of("/images/rakan.png")));
        entities.add(new EntityPathPair(new Entity("Rammus"), Path.of("/images/rammus.png")));
        entities.add(new EntityPathPair(new Entity("Rek'Sai"), Path.of("/images/reksai.png")));
        entities.add(new EntityPathPair(new Entity("Rell"), Path.of("/images/rell.png")));
        entities.add(new EntityPathPair(new Entity("Renata Glasc"), Path.of("/images/renataglasc.png")));
        entities.add(new EntityPathPair(new Entity("Renekton"), Path.of("/images/renekton.png")));
        entities.add(new EntityPathPair(new Entity("Rengar"), Path.of("/images/rengar.png")));
        entities.add(new EntityPathPair(new Entity("Riven"), Path.of("/images/riven.png")));
        entities.add(new EntityPathPair(new Entity("Rumble"), Path.of("/images/rumble.png")));
        entities.add(new EntityPathPair(new Entity("Ryze"), Path.of("/images/ryze.png")));
        entities.add(new EntityPathPair(new Entity("Samira"), Path.of("/images/samira.png")));
        entities.add(new EntityPathPair(new Entity("Smolder"), Path.of("/images/smolder.png")));
        entities.add(new EntityPathPair(new Entity("Sejuani"), Path.of("/images/sejuani.png")));
        entities.add(new EntityPathPair(new Entity("Senna"), Path.of("/images/senna.png")));
        entities.add(new EntityPathPair(new Entity("Seraphine"), Path.of("/images/seraphine.png")));
        entities.add(new EntityPathPair(new Entity("Sett"), Path.of("/images/sett.png")));
        entities.add(new EntityPathPair(new Entity("Shaco"), Path.of("/images/shaco.png")));
        entities.add(new EntityPathPair(new Entity("Shen"), Path.of("/images/shen.png")));
        entities.add(new EntityPathPair(new Entity("Shyvana"), Path.of("/images/shyvana.png")));
        entities.add(new EntityPathPair(new Entity("Singed"), Path.of("/images/singed.png")));
        entities.add(new EntityPathPair(new Entity("Sion"), Path.of("/images/sion.png")));
        entities.add(new EntityPathPair(new Entity("Sivir"), Path.of("/images/sivir.png")));
        entities.add(new EntityPathPair(new Entity("Skarner"), Path.of("/images/skarner.png")));
        entities.add(new EntityPathPair(new Entity("Sona"), Path.of("/images/sona.png")));
        entities.add(new EntityPathPair(new Entity("Soraka"), Path.of("/images/soraka.png")));
        entities.add(new EntityPathPair(new Entity("Swain"), Path.of("/images/swain.png")));
        entities.add(new EntityPathPair(new Entity("Sylas"), Path.of("/images/sylas.png")));
        entities.add(new EntityPathPair(new Entity("Syndra"), Path.of("/images/syndra.png")));
        entities.add(new EntityPathPair(new Entity("Tahm Kench"), Path.of("/images/tahmkench.png")));
        entities.add(new EntityPathPair(new Entity("Taliyah"), Path.of("/images/taliyah.png")));
        entities.add(new EntityPathPair(new Entity("Talon"), Path.of("/images/talon.png")));
        entities.add(new EntityPathPair(new Entity("Taric"), Path.of("/images/taric.png")));
        entities.add(new EntityPathPair(new Entity("Teemo"), Path.of("/images/teemo.png")));
        entities.add(new EntityPathPair(new Entity("Thresh"), Path.of("/images/thresh.png")));
        entities.add(new EntityPathPair(new Entity("Tristana"), Path.of("/images/tristana.png")));
        entities.add(new EntityPathPair(new Entity("Trundle"), Path.of("/images/trundle.png")));
        entities.add(new EntityPathPair(new Entity("Tryndamere"), Path.of("/images/tryndamere.png")));
        entities.add(new EntityPathPair(new Entity("Twisted Fate"), Path.of("/images/twistedfate.png")));
        entities.add(new EntityPathPair(new Entity("Twitch"), Path.of("/images/twitch.png")));
        entities.add(new EntityPathPair(new Entity("Udyr"), Path.of("/images/udyr.png")));
        entities.add(new EntityPathPair(new Entity("Urgot"), Path.of("/images/urgot.png")));
        entities.add(new EntityPathPair(new Entity("Varus"), Path.of("/images/varus.png")));
        entities.add(new EntityPathPair(new Entity("Vayne"), Path.of("/images/vayne.png")));
        entities.add(new EntityPathPair(new Entity("Vex"), Path.of("/images/vex.png")));
        entities.add(new EntityPathPair(new Entity("Veigar"), Path.of("/images/veigar.png")));
        entities.add(new EntityPathPair(new Entity("Vel'Koz"), Path.of("/images/velkoz.png")));
        entities.add(new EntityPathPair(new Entity("Vi"), Path.of("/images/vi.png")));
        entities.add(new EntityPathPair(new Entity("Viego"), Path.of("/images/viego.png")));
        entities.add(new EntityPathPair(new Entity("Viktor"), Path.of("/images/viktor.png")));
        entities.add(new EntityPathPair(new Entity("Vladimir"), Path.of("/images/vladimir.png")));
        entities.add(new EntityPathPair(new Entity("Volibear"), Path.of("/images/volibear.png")));
        entities.add(new EntityPathPair(new Entity("Warwick"), Path.of("/images/warwick.png")));
        entities.add(new EntityPathPair(new Entity("Wukong"), Path.of("/images/wukong.png")));
        entities.add(new EntityPathPair(new Entity("Xayah"), Path.of("/images/xayah.png")));
        entities.add(new EntityPathPair(new Entity("Xerath"), Path.of("/images/xerath.png")));
        entities.add(new EntityPathPair(new Entity("Xin Zhao"), Path.of("/images/xinzhao.png")));
        entities.add(new EntityPathPair(new Entity("Yasuo"), Path.of("/images/yasuo.png")));
        entities.add(new EntityPathPair(new Entity("Yone"), Path.of("/images/yone.png")));
        entities.add(new EntityPathPair(new Entity("Yorick"), Path.of("/images/yorick.png")));
        entities.add(new EntityPathPair(new Entity("Yunara"), Path.of("/images/yunara.png")));
        entities.add(new EntityPathPair(new Entity("Yuumi"), Path.of("/images/yuumi.png")));
        entities.add(new EntityPathPair(new Entity("Zac"), Path.of("/images/zac.png")));
        entities.add(new EntityPathPair(new Entity("Zaahen"), Path.of("/images/zaahen.png")));
        entities.add(new EntityPathPair(new Entity("Zed"), Path.of("/images/zed.png")));
        entities.add(new EntityPathPair(new Entity("Zeri"), Path.of("/images/zeri.png")));
        entities.add(new EntityPathPair(new Entity("Ziggs"), Path.of("/images/ziggs.png")));
        entities.add(new EntityPathPair(new Entity("Zilean"), Path.of("/images/zilean.png")));
        entities.add(new EntityPathPair(new Entity("Zoe"), Path.of("/images/zoe.png")));
        entities.add(new EntityPathPair(new Entity("Zyra"), Path.of("/images/zyra.png")));

        return entities;
    }
}
